# Generated by Django 5.0.4 on 2024-04-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("address_line_1", models.CharField(blank=True, max_length=255, verbose_name="adresse")),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Appartement, suite, bloc, bâtiment, boite postale, etc.",
                        max_length=255,
                        verbose_name="complément d'adresse",
                    ),
                ),
                ("post_code", models.CharField(blank=True, max_length=5, verbose_name="code postal")),
                ("city", models.CharField(blank=True, max_length=255, verbose_name="ville")),
                ("label_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="id LABEL")),
                ("created_at", models.DateTimeField(null=True, verbose_name="date de création")),
                ("last_name", models.CharField(verbose_name="nom de famille")),
                ("first_name", models.CharField(verbose_name="prénom")),
                ("birthdate", models.DateField(verbose_name="date de naissance")),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Monsieur"), ("MME", "Madame")],
                        default="",
                        max_length=3,
                        verbose_name="civilité",
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SQ", "Sans qualification"),
                            ("N3", "Niveau 3 (CAP, BEP)"),
                            ("N4", "Niveau 4 (BP, Bac Général, Techno ou Pro, BT)"),
                            ("N5", "Niveau 5 ou + (Bac+2 ou +)"),
                        ],
                        default="",
                        max_length=2,
                        verbose_name="niveau de qualifacation à l'entrée obtenu",
                    ),
                ),
                ("other_data", models.JSONField(verbose_name="autres données")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GEIQAntenna",
            fields=[
                ("address_line_1", models.CharField(blank=True, max_length=255, verbose_name="adresse")),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Appartement, suite, bloc, bâtiment, boite postale, etc.",
                        max_length=255,
                        verbose_name="complément d'adresse",
                    ),
                ),
                ("post_code", models.CharField(blank=True, max_length=5, verbose_name="code postal")),
                ("city", models.CharField(blank=True, max_length=255, verbose_name="ville")),
                ("label_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="id LABEL")),
                ("name", models.CharField(verbose_name="nom")),
                ("created_at", models.DateTimeField(null=True, verbose_name="date de création")),
                ("siret", models.CharField(blank=True, verbose_name="siret")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="téléphone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GEIQLabelInfo",
            fields=[
                ("address_line_1", models.CharField(blank=True, max_length=255, verbose_name="adresse")),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Appartement, suite, bloc, bâtiment, boite postale, etc.",
                        max_length=255,
                        verbose_name="complément d'adresse",
                    ),
                ),
                ("post_code", models.CharField(blank=True, max_length=5, verbose_name="code postal")),
                ("city", models.CharField(blank=True, max_length=255, verbose_name="ville")),
                ("label_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="id LABEL")),
                ("name", models.CharField(verbose_name="nom")),
                ("created_at", models.DateTimeField(null=True, verbose_name="date de création")),
                ("siret", models.CharField(blank=True, verbose_name="siret")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="téléphone")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="e-mail")),
                ("ffgeiq_member", models.BooleanField(verbose_name="adherent FFGEIQ")),
                ("other_data", models.JSONField(verbose_name="autres données")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeContract",
            fields=[
                ("label_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="id LABEL")),
                ("other_data", models.JSONField(verbose_name="autres données")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contracts", to="geiq.employee"
                    ),
                ),
                (
                    "antenna",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="geiq.geiqantenna",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="geiqantenna",
            name="geiq",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="antennas", to="geiq.geiqlabelinfo"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="geiq",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="employees", to="geiq.geiqlabelinfo"
            ),
        ),
    ]
