# Generated by Django 5.0.4 on 2024-04-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geiqlabelinfo",
            name="last_synced_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
