# Generated by Django 5.0.4 on 2024-05-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0002_geiqlabelinfo_last_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SQ", "Sans qualification"),
                    ("N3", "Niveau 3 (CAP, BEP)"),
                    ("N4", "Niveau 4 (BP, Bac Général, Techno ou Pro, BT)"),
                    ("N5", "Niveau 5 ou + (Bac+2 ou +)"),
                ],
                default="",
                verbose_name="niveau de qualification à l'entrée obtenu",
            ),
        ),
        migrations.AlterField(
            model_name="geiqlabelinfo",
            name="last_synced_at",
            field=models.DateTimeField(verbose_name="dernière synchronisation à"),
        ),
        migrations.CreateModel(
            name="EmployeePrequalification",
            fields=[
                ("label_id", models.IntegerField(primary_key=True, serialize=False, verbose_name="id LABEL")),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AFPR", "AFPR"),
                            ("DISPOSITIF", "Dispositif régional ou sectoriel"),
                            ("POE", "POE"),
                            ("AUTRE", "AUTRE"),
                        ],
                        default="",
                        verbose_name="type d'action",
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="date de début")),
                ("end_at", models.DateTimeField(verbose_name="date de fin")),
                ("training_hours_nb", models.PositiveIntegerField(verbose_name="nombre d'heures de formation")),
                ("other_data", models.JSONField(verbose_name="autres données")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prequalifications",
                        to="geiq.employee",
                    ),
                ),
            ],
        ),
    ]
