# Generated by Django 5.0.4 on 2024-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0003_alter_employee_qualification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="prescriber_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEMANDEUR_EMPLOI", "Demandeur d'emploi"),
                    ("PRESCRIPTEUR", "Prescripteur"),
                    ("EMPLOYEUR", "Employeur"),
                    ("AUTRE", "Autre"),
                ],
                default="",
                verbose_name="type de prescripteur",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprequalification",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AFPR", "AFPR"),
                    ("DISPOSITIF", "Dispositif régional ou sectoriel"),
                    ("POE", "POE"),
                    ("AUTRE", "Autre"),
                ],
                default="",
                verbose_name="type d'action",
            ),
        ),
    ]
