# Generated by Django 5.0.4 on 2024-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0004_employee_prescriber_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="nb_hours_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="nombre d'heures par semaine"),
        ),
    ]
