# Generated by Django 5.0.4 on 2024-05-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0005_employeecontract_nb_hours_per_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeecontract",
            name="contract_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CPRO", "Contrat de professionnalisation"),
                    ("CAPP", "Contrat d'apprentissage"),
                    ("CUI+F", "CUI (toute catégorie)"),
                    ("CDD+CPF", "CDD - CPF"),
                    ("CDD+autre", "CDD - Autre"),
                    ("Autre F", "Autre (avec formation)"),
                    ("CUI", "CUI (toute catégorie)"),
                    ("CDD", "CDD"),
                    ("CDI", "CDI"),
                    ("Autre SF", "Autre (sans formation)"),
                ],
                default="",
                verbose_name="nature du contrat",
            ),
        ),
    ]
