# Generated by Django 5.0.4 on 2024-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0006_employeecontract_contract_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecontract",
            name="nb_hours_per_week",
            field=models.FloatField(blank=True, null=True, verbose_name="nombre d'heures par semaine"),
        ),
    ]
