# Generated by Django 5.0.4 on 2024-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0007_alter_employeecontract_nb_hours_per_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeecontract",
            name="end_at",
            field=models.DateField(null=True, verbose_name="date de fin"),
        ),
        migrations.AlterField(
            model_name="employeecontract",
            name="planned_end_at",
            field=models.DateField(verbose_name="date de fin prévisionnelle"),
        ),
        migrations.AlterField(
            model_name="employeecontract",
            name="start_at",
            field=models.DateField(verbose_name="date de début"),
        ),
        migrations.AlterField(
            model_name="employeeprequalification",
            name="end_at",
            field=models.DateField(verbose_name="date de fin"),
        ),
        migrations.AlterField(
            model_name="employeeprequalification",
            name="start_at",
            field=models.DateField(verbose_name="date de début"),
        ),
    ]
