# Generated by Django 5.0.4 on 2024-05-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geiq", "0008_alter_employeecontract_end_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeecontract",
            name="antenna",
        ),
        migrations.DeleteModel(
            name="GEIQAntenna",
        ),
    ]
